"""Generate fig01 schematic assets: X / X_recon / H_t images and the custom-sigmoid
legend plot (matching the paper-style inset showing how the hardening parameter m
sharpens the excitation-pattern sigmoid).

X / X_recon / H_t are regenerated by *running inference* with the same
``bbbc022_content_aware_v2`` checkpoints and specimen-selection logic as
``render_fig03_content_aware.py`` (common test specimen, percentile=65), so they
are pixel-identical in derivation to Figure 3's panel F (ground truth) and the
x16/learnable-frequency cell of panel A (reconstruction) -- NOT the earlier
``bbbc022_content_aware`` (non-"v2") grayscale mosaics. H_t uses the x64/
learnable-frequency model's most-structured pattern channel, i.e. Figure 3
panel C2's "downscale 16x16" pattern (per ``DOWNSCALE = {"x64": 16, ...}`` in
``render_fig03_content_aware.py``), as requested.

Usage (from `replication/`):
    .venv/bin/python scripts/render_fig01_assets.py
"""
from __future__ import annotations

import sys
from pathlib import Path

import matplotlib
import matplotlib.font_manager as fm
import numpy as np
import torch

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parents[2]
REPL_ROOT = REPO_ROOT / "replication"
SRC = REPL_ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from models.microscope import DifferentiableMicroscope  # noqa: E402
from training.dataloaders import build_dataloader  # noqa: E402
from utils.device import resolve_device  # noqa: E402
from utils.experiment_config import load_experiment_config  # noqa: E402

FIG01 = REPO_ROOT / "paper_ready_results/02_main_figures/fig01_differentiable_microscopy_schematic"
OUT_COMPONENTS = FIG01 / "components"
OUT_RENDERED = FIG01 / "rendered"

EXP_ROOT = REPL_ROOT / "experiments/figure03_content_aware/base"
PERCENTILE = 65.0  # matches render_fig03_content_aware.py default (common test specimen)


def run_dir(comp: str, method: str) -> Path:
    return EXP_ROOT / f"bbbc022_{comp}_{method}_seed42"


def load_model(config, ckpt: Path, device: torch.device, image_size: int) -> DifferentiableMicroscope:
    model = DifferentiableMicroscope.from_run_config(config).to(device)
    model(torch.zeros(1, 1, image_size, image_size, device=device), sigmoid_m=10.0, apply_noise=False)
    payload = torch.load(ckpt, map_location=device, weights_only=False)
    model.load_state_dict(payload["model_state_dict"])
    model.eval()
    return model


def select_test_specimen(loader, percentile: float):
    specimens = []
    for batch in loader:
        specimen = batch if torch.is_tensor(batch) else batch[0]
        specimens.append(specimen)
    x = torch.cat(specimens, dim=0)
    frac = (x > 0.3).float().mean(dim=(1, 2, 3)).cpu().numpy()
    target = np.percentile(frac, percentile)
    idx = int(np.argmin(np.abs(frac - target)))
    return x[idx : idx + 1], idx


def robust_norm(img: np.ndarray, lo: float = 1.0, hi: float = 99.0) -> tuple[float, float]:
    return float(np.percentile(img, lo)), float(np.percentile(img, hi))


def compute_arrays(device: torch.device) -> dict[str, np.ndarray]:
    ref_cfg = load_experiment_config(run_dir("x16", "hadamard_fixed") / "config.yaml")
    ref_cfg["experiment"]["device"] = str(device)
    image_size = ref_cfg["dataset"]["image_size"]
    test_loader = build_dataloader(ref_cfg, "test")
    specimen, chosen_idx = select_test_specimen(test_loader, PERCENTILE)
    specimen = specimen.to(device)
    print(f"[fig1-assets] common test specimen index = {chosen_idx}")

    gt = specimen[0, 0].cpu().numpy()

    cfg16 = load_experiment_config(run_dir("x16", "learnable_frequency") / "config.yaml")
    cfg16["experiment"]["device"] = str(device)
    model16 = load_model(cfg16, run_dir("x16", "learnable_frequency") / "checkpoints" / "best.pt", device, image_size)
    with torch.no_grad():
        out16 = model16(specimen, sigmoid_m=10.0, apply_noise=False)
    recon = out16["x_recon"][0, 0].clamp(0, 1).cpu().numpy()
    del model16

    # H_t: x64/learnable_frequency -> downscale_factor=16 -> Fig.3 C2 "downscale 16x16".
    cfg64 = load_experiment_config(run_dir("x64", "learnable_frequency") / "config.yaml")
    cfg64["experiment"]["device"] = str(device)
    model64 = load_model(cfg64, run_dir("x64", "learnable_frequency") / "checkpoints" / "best.pt", device, image_size)
    with torch.no_grad():
        out64 = model64(specimen, sigmoid_m=10.0, apply_noise=False)
    p_all = out64["patterns"][:, 0].cpu().numpy()  # [T,H,W]
    ch = int(np.argmax(p_all.reshape(p_all.shape[0], -1).var(axis=1)))
    pattern = p_all[ch]
    del model64

    return {"gt": gt, "recon": recon, "pattern": pattern}


def save_clean_image(img: np.ndarray, out_path: Path, *, cmap: str, vmin: float, vmax: float,
                     interpolation: str) -> None:
    """Save a bare image (no title/axes/colorbar/margins) at native resolution."""
    h, w = img.shape
    dpi = 200
    fig = plt.figure(figsize=(w / dpi, h / dpi), dpi=dpi)
    ax = fig.add_axes([0, 0, 1, 1])
    ax.imshow(img, cmap=cmap, vmin=vmin, vmax=vmax, interpolation=interpolation)
    ax.axis("off")
    fig.savefig(out_path, dpi=dpi)
    plt.close(fig)
    print("wrote", out_path)


def render_crops() -> None:
    device = resolve_device("cpu")
    arrays = compute_arrays(device)

    save_clean_image(arrays["gt"], OUT_COMPONENTS / "panel_X_ground_truth_x16.png",
                     cmap="viridis", vmin=0.0, vmax=1.0, interpolation="bilinear")
    save_clean_image(arrays["recon"], OUT_COMPONENTS / "panel_Xrecon_learnable_x16.png",
                     cmap="viridis", vmin=0.0, vmax=1.0, interpolation="bilinear")
    lo, hi = robust_norm(arrays["pattern"], 1, 99)
    if hi <= lo:
        hi = lo + 1e-6
    save_clean_image(arrays["pattern"], OUT_COMPONENTS / "panel_Ht_pattern_ds16.png",
                     cmap="gray", vmin=lo, vmax=hi, interpolation="nearest")


def render_sigmoid_legend() -> None:
    fm.fontManager.addfont("/usr/share/fonts/truetype/msttcorefonts/Arial.ttf")
    plt.rcParams["font.family"] = "Arial"

    x = np.linspace(-3, 3, 1000)
    colors = {1: "#1f77b4", 3: "#ff7f0e", 10: "#2ca02c"}  # matplotlib C0/C1/C2, matches paper inset
    legend_fontsize = 7

    fig = plt.figure(figsize=(1.36, 0.64), dpi=600)  # w=1.36in, h=0.64in (requested output size)
    ax = fig.add_axes([0, 0, 1, 1])
    for m, c in colors.items():
        y = 1.0 / (1.0 + np.exp(-m * x))
        ax.plot(x, y, color=c, linewidth=1.0, label=f"m : {m}")

    ax.set_xlim(x.min(), x.max())
    ax.set_ylim(-0.05, 1.05)
    ax.axis("off")  # no axes/ticks, as requested

    legend = ax.legend(
        loc="center left",
        bbox_to_anchor=(0.02, 0.5),
        frameon=True,
        fontsize=legend_fontsize,
        handlelength=1.3,
        handletextpad=0.4,
        labelspacing=0.3,
        borderpad=0.4,
        borderaxespad=0.0,
        prop=fm.FontProperties(family="Arial", size=legend_fontsize),
    )
    legend.get_frame().set_edgecolor("#bfbfbf")
    legend.get_frame().set_facecolor("white")
    legend.get_frame().set_linewidth(0.6)
    legend.get_frame().set_alpha(0.95)

    for out_dir in (OUT_RENDERED, OUT_COMPONENTS):
        fig.savefig(out_dir / "sigmoid_m_legend.png", dpi=600, transparent=True)
    fig.savefig(OUT_RENDERED / "sigmoid_m_legend.svg", transparent=True)
    fig.savefig(OUT_RENDERED / "sigmoid_m_legend.pdf", transparent=True)
    print("wrote sigmoid legend plot(s)")


if __name__ == "__main__":
    OUT_COMPONENTS.mkdir(parents=True, exist_ok=True)
    OUT_RENDERED.mkdir(parents=True, exist_ok=True)
    render_crops()
    render_sigmoid_legend()
